Repository openyurtio/kole, pull requests merged in 2022-02, with the labels that each got.

#2 Add owners and pull request template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  OWNERS
Labels: lgtm

#3 Rename InfDaemonSet CRD to KoleDaemonSet CRD
  config/crd/lite.openyurt.io_koledaemonsets.yaml
  config/rbac/role.yaml
  config/setup/manifest.yaml
  go.mod
  go.sum
  pkg/apis/lite/v1alpha1/koledaemonset_types.go
  pkg/apis/lite/v1alpha1/register.go
  pkg/apis/lite/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/lite/v1alpha1/fake/fake_infdaemonset.go
  pkg/client/clientset/versioned/typed/lite/v1alpha1/fake/fake_koledaemonset.go
  pkg/client/clientset/versioned/typed/lite/v1alpha1/fake/fake_lite_client.go
  pkg/client/clientset/versioned/typed/lite/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/lite/v1alpha1/infdaemonset.go
  pkg/client/clientset/versioned/typed/lite/v1alpha1/koledaemonset.go
  pkg/client/clientset/versioned/typed/lite/v1alpha1/lite_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/lite/v1alpha1/interface.go
  pkg/client/informers/externalversions/lite/v1alpha1/koledaemonset.go
  pkg/client/listers/lite/v1alpha1/expansion_generated.go
  pkg/client/listers/lite/v1alpha1/infdaemonset.go
  pkg/client/listers/lite/v1alpha1/koledaemonset.go
  pkg/kolecontroller/consumeHeartBeat.go
  pkg/kolecontroller/consumeHeartBeat_test.go
  pkg/kolecontroller/kole_controller.go
  pkg/kolecontroller/kole_controller_heartbeatcache.go
  pkg/kolecontroller/koledaemonset_controller.go
  vendor/github.com/imdario/mergo/.deepsource.toml
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/modules.txt
Labels: approved, kind/enhancement, size/XXL

#4 fix work flow bug
  .github/workflows/go.yml
  Makefile
  hack/lib/generate.sh
  pkg/apis/lite/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#5 Remove InfEdgeNode CRD
  cmd/kole-controller/app/server.go
  cmd/stormtest/cmd/create/create_infedgenodes.go
  cmd/stormtest/cmd/delete/delete_infedgenodes.go
  cmd/stormtest/cmd/load/load_infedgenodes.go
  cmd/stormtest/cmd/options/compression_options.go
  cmd/stormtest/cmd/options/create_infedgenode_options.go
  cmd/stormtest/cmd/options/delete_infedgenode_options.go
  cmd/stormtest/cmd/options/globaloptions.go
  config/crd/lite.openyurt.io_infedgenodes.yaml
  config/setup/manifest.yaml
  pkg/apis/lite/v1alpha1/infnode_types.go
  pkg/apis/lite/v1alpha1/register.go
  pkg/apis/lite/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/lite/v1alpha1/fake/fake_infedgenode.go
  pkg/client/clientset/versioned/typed/lite/v1alpha1/fake/fake_lite_client.go
  pkg/client/clientset/versioned/typed/lite/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/lite/v1alpha1/infedgenode.go
  pkg/client/clientset/versioned/typed/lite/v1alpha1/lite_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/lite/v1alpha1/infedgenode.go
  pkg/client/informers/externalversions/lite/v1alpha1/interface.go
  pkg/client/listers/lite/v1alpha1/expansion_generated.go
  pkg/client/listers/lite/v1alpha1/infedgenode.go
  pkg/controller/compress.go
  pkg/controller/compress_test.go
  pkg/controller/consumeHeartBeat.go
  pkg/controller/consumeHeartBeat_test.go
  pkg/controller/kole_controller.go
  pkg/controller/kole_controller_desiredpodcache.go
  pkg/controller/kole_controller_heartbeatcache.go
  pkg/controller/kole_controller_heatbeatfilter.go
  pkg/controller/kole_controller_observerdpodcache.go
  pkg/controller/kole_controller_querynodestatuscache.go
  pkg/controller/koledaemonset_controller.go
  pkg/controller/querynode_controller.go
  pkg/controller/snapshot.go
  pkg/controller/snapshot_test.go
  pkg/controller/sort.go
  pkg/controller/sort_test.go
  pkg/controller/sub.go
  pkg/controller/sub5.go
  pkg/kolecontroller/kole_controller_heartbeatcache.go
  pkg/stormtest/compresscrs_test.go
  pkg/stormtest/compression.go
  pkg/stormtest/create_infedgenode.go
  pkg/stormtest/delete_infedgenodes.go
  pkg/stormtest/load_infedgenodes.go
  pkg/stormtest/node_template.go
  test/e2e/contumeheatbeat/main.go
Labels: approved, lgtm, size/XXL

#7 Cleanup: remove non-english comments
  pkg/controller/compress.go
  pkg/controller/kolequery_controller.go
  pkg/controller/snapshot.go
  pkg/litekubelet/litekubelet.go
  pkg/stormtest/consume_rocketmq.go
  test/e2e/consumeheatbeat/main.go
  test/script/crds/koledaemonset.yaml
  test/script/crds/kolequery.yaml
  test/script/nodetest.sh
Labels: approved, lgtm, size/L
